### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by kiteretro** [trollcop/m4osd#1]
Hi, could you make any schematics available? I have a rough idea based on the board.h how it goes together but would be better if I had some basic schematic :) If you would like to PM me (instead of making public) then gilesburgess2[at]hotmail.com will work!

**Comment by trollcop** [comment]
Sorry, late reply.
The schematics are not really useful because there are issues with analog portion. I wouldn't want you to clone something that's not really a great schema.

Maybe at some point I'll have time to revisit this project.

**Comment by kiteretro** [comment]
Thanks for the reply, I think this project has legs as an open source STM OSD (to replace the MAX7456 based OSDs) would be massively welcome! I originally asked as I am looking at doing something similar and experimenting around with ideas.. I hope you do pick it up at some point, the TauLabs project uses dual SPI and DMA to provide a good OSD so there is code out there, but very little schematics ;) Thanks again, I'll close this issue.

**Comment by trollcop** [comment]
Yeah, I totally agree. The MAX shit needs to die.
there are schematics for tau stuff, I thought their requirement was being
opensores?

The simplest way is just a analog switch that gets toggled between Vin and
one of several voltages (representing NTSC white, NTSC black).

This is the switch that gets toggled by DMA'd SPI channels.

**Comment by kiteretro** [comment]
Totally, MAX + 328p isn't great..

You are correct I believe, they use the F4's DAC to provide the voltage as far as I can tell.. I didn't spend long digging so perhaps I'll revisit and search there for the schematics and start prototyping something.. Thanks for your help, all the best!

**Comment by trollcop** [comment]
I've considered using dac, but unless you want changeable brightness levels
(usually you don't), just using resistor dividers to get NTSC voltages is
enough.
